spring:
  profiles:
    group:
      local: "dev, common, secret-dev"
      prod: "prod, common, secret-prod"
      test: "test, common, secret-test"
    include: secret
    active: local
---
spring:
  config:
    activate:
      on-profile: common
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
jwt:
  access:
    expiration: 900000 # 15분
    header: Authorization
  refresh:
    expiration: 86400000 #  1일
    header: Authorization-refresh
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
server:
  port: 9999