spring:
  profiles:
    group:
      local: "dev, common, secret-common, secret-dev"
      prod: "prod, common, secret-common, secret-prod"
      test: "test, common, secret-common, secret-test"
    include: secret
    active: local
---
spring:
  application:
    name: user-service
    config:
    activate:
      on-profile: common

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
jwt:
  access:
    expiration: 900000 # 15분
    header: Authorization
  refresh:
    expiration: 86400000 #  1일
    header: Authorization-refresh

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 5
    instances:
      case1:
        baseConfig: default
        failureRateThreshold: 10  # 10% 실패율에 서킷 브레이커가 열림
      case2:
        baseConfig: default
        failureRateThreshold: 20  # 타임아웃 실패율을 감지할 경우 사용
      case3:
        baseConfig: default
        failureRateThreshold: 50  # 특정 시간대에 50% 이상의 실패율에 서킷 브레이커가 열림
  retry:
    instances:
      case1:
        maxAttempts: 3  # 최대 3번 재시도
        waitDuration: 1s  # 재시도 사이의 대기 시간
      case2:
        maxAttempts: 3
        waitDuration: 1s
      case3:
        maxAttempts: 3
        waitDuration: 1s
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 8887

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 30
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      item-service:
        url: http://localhost:8889
        connect-timeout: 5000
        read-timeout: 5000

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 30
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

feign:
  client:
    config:
      item-service:
        url: http://item-service:8082
        connectTimeout: 5000
        readTimeout: 5000

---
spring:
  config:
    activate:
      on-profile: test

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
feign:
  client:
    config:
      item-service:
        url: http://localhost:8889