spring:
  application:
    name: order-service
  profiles:
    group:
      local: "common, dev, secret-dev"
      prod: "common, prod, secret-prod"
      test: "test, secret-test"
    include: secret
    active: local
---
spring:
  config:
    activate:
      on-profile: common
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 30
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 5
    instances:
      getItem:
        baseConfig: default
        failureRateThreshold: 10  # 10% 실패율에 서킷 브레이커가 열림
      increaseStock:
        baseConfig: default
        failureRateThreshold: 10  # 10% 실패율에 서킷 브레이커가 열림
      decreaseStock:
        baseConfig: default
        failureRateThreshold: 10  # 10% 실패율에 서킷 브레이커가 열림
      getStock:
        baseConfig: default
        failureRateThreshold: 10  # 10% 실패율에 서킷 브레이커가 열림
      getUserByEmail:
        baseConfig: default
        failureRateThreshold: 10  # 타임아웃 실패율을 감지할 경우 사용
      initiatePayment:
        baseConfig: default
        failureRateThreshold: 10  # 타임아웃 실패율을 감지할 경우 사용
      completePayment:
        baseConfig: default
        failureRateThreshold: 10  # 타임아웃 실패율을 감지할 경우 사용

  retry:
    instances:
      getItem:
        maxAttempts: 3  # 최대 3번 재시도
        waitDuration: 1s  # 재시도 사이의 대기 시간
      increaseStock:
        maxAttempts: 3
        waitDuration: 1s
      decreaseStock:
        maxAttempts: 3
        waitDuration: 1s
      getStock:
        maxAttempts: 3
        waitDuration: 1s
      getUserByEmail:
        maxAttempts: 3
        waitDuration: 1s
      initiatePayment:
        maxAttempts: 3
        waitDuration: 1s
      completePayment:
        maxAttempts: 3
        waitDuration: 1s
---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      item-service:
        url: http://localhost:8889
      user-service:
        url: http://localhost:8887
      payment-service:
        url: http://localhost:8886

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

feign:
  client:
    config:
      item-service:
        url: http://item-service:8082
      user-service:
        url: http://user-service:8080
      payment-service:
        url: http://payment-service:8079

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
  cloud:
    gateway:
      enabled: false

eureka:
  client:
    enabled: false

feign:
  client:
    config:
      item-service:
        url: http://localhost:8889
      user-service:
        url: http://localhost:8887
      payment-service:
        url: http://localhost:8886